### ISSUE TITLE
Peopozycje

### ISSUE THREAD

**Issue by Aldmors** [florczaq/PKWM-Timetable#2]
1. Dużym uwygodnieniem byłoby podawanie daty kalendarzowej przy nazwie dnia tygodnia.

2. Dodatkowo do dałbym możliwość wybierania tygodnia na podstawie kalendarza.

3. Czasami zdarza się, że jedna osoba może być przypisana do kilku grup zajęciowych np. ktoś może być przypisany do k01 jednak na jednym przedmiocie będzie w k03. Często taka sytuacja występuje na specjalizacji. Można by dodać opcje "zaawansowane" i możliwość manualnego wybrania grupy na dane przedmioty.

**Comment by florczaq** [comment]
Aplikacja jest wersją mobilną rozkładu zajęć dostępnego na stronie wydziału. Ma ona ułatwić czytanie go, szczególnie dla nowych studentów. 
Ad 1 i 2:
       Uzależnienie działania aplikacji od kalendarza mogło by powodować dodatkowe błędy w działaniu i okazać sie problematyczne przy np. jednorazowej zmianie tygodnia parzystego na nieparzysty. Prosto mówiąc taka zmiana powodowała by więcej problemów niż pożytku.


Ad 3:
      Jest to celna uwaga. Jak wspomniałem wyżej jest to aplikacja szczegolnie dedykowana nowym studentom, awięc nie przykuwałem tak dużej uwagi do specjalizacji. Sam nie mam duzej wiedzy o działaniu rozkładu zajęć na specjalizacjach, ale po zbadaniu tematu jest to jak najbardziej do zdobienia.
